FROM python:3.10-slim

WORKDIR /app

RUN pip install --no-cache-dir uv

COPY requirements-worker.txt .
RUN uv pip install --system --no-cache --index-strategy unsafe-best-match --prerelease=allow -r requirements-worker.txt

COPY . .